### ISSUE TITLE
not working on palera1n rootless 15.7.5

### ISSUE THREAD

**Issue by iAroc** [opa334/opainject#1]
heyya

Just saw this, and im wondering if its even supports rootless in the first place.

The app can be started, but when i try to inject, i get the following error codes, and my dylib doesnt load:

```
# ./opainject 5679 /var/tmp/MyTest.dylib                                                                                                                                                   
OPAINJECT HERE WE ARE
RUNNING AS 0
Got task port 2563 for pid 5679!
[prepareForMagic] done, ropLoop: 0x10A879B14
[createRemotePthread] Created bootstrap thread... now waiting on finish
[createRemotePthread] Bootstrap done!
[createRemotePthread] Found pthread: 15363
[sandboxFixup] applying sandbox extension! sandbox_extension_consume: 0x1DC999280
[arbCall] Set thread state for arbitary call
[arbCall] Started thread, waiting for it to finish...
[sandboxFixup] sandbox_extension_consume returned 1
[injectDylibViaRop] Preparation done, now injecting!
[injectDylibViaRop] dlopen: 0x181304234, dlerror: 0x181305788
[arbCall] Set thread state for arbitary call
[arbCall] Started thread, waiting for it to finish...
```

im running it after i ssh to my phone

**Comment by opa334** [comment]
Not sure what's the issue here, seems like the thread never finished... Could also be an infinite loop in your dylib maybe?

**Comment by iAroc** [comment]
Okay, so i found the issue. it was really in my tweak, but its not a loop or anything.
As soon i try to swizzle some objc method, and have any code in the load segment, it just froze the app for me, and thus the injection thread never ended.

i fixed it by simply moving my method swizzling into another thread, e.g.
```@implementation UIApplication(Swizzle)
+ (void)load {
	std::thread([](void* self1) {
		// .... do stuff
	}, (__bridge void*)self).detach();
}
```

and now everything works. so this issue can be closed, but might help someone else when they google for it
