### ISSUE TITLE
Cannot Inject on iOS 16.5 Rootless Palera1n

### ISSUE THREAD

**Issue by iAroc** [opa334/opainject#2]
Heyya

Currently trying to Inject a dylib into a Process on ios 16.5, an iPhone 8.

Right now, my target process is SpringBoard, and the dylib is just this code:
```
__attribute__((constructor))
static void customConstructor() {
    NSLog(@"Test loaded");
}
```

however, when i execute opainject on my phone, the process gets killed. Thats the output before the kill:
```
OPAINJECT HERE WE ARE
RUNNING AS 0
Got task port 7427 for pid 35!
[prepareForMagic] done, ropLoop: 0x19594B5F4
[createRemotePthread] Created bootstrap thread... now waiting on finish
[createRemotePthread] Bootstrap done!
[createRemotePthread] WARNING: failed to get thread state of thread 0 when trying to find pthread, error: (ipc/send) invalid destination port (268435459)
[createRemotePthread] Found pthread: 4355
[sandboxFixup] not needed, bailing out.
[injectDylibViaRop] Preparation done, now injecting!
[injectDylibViaRop] dlopen: 0x1BAD28C04, dlerror: 0x1BAD2A0F4
Killed 
```

I tried to run opainject as root and as mobile user, to see if it makes any difference. but it does not.

after adding some logs, i found the crashing line is this one here:
https://github.com/opa334/opainject/blob/main/rop_inject.m#L321

but i dont have any clue whats the problem or how to fix it. 

Would be nice if you can fix it. If you need any more logs or infos from me, im happy to help

**Comment by opa334** [comment]
16.4 broke several thread related APIs, I looked into this before but it seems very hard to fix although there might be an easy way out as debuggers also need these APIs, maybe it now checks whether the target process is traced via ptrace... Not sure.

**Comment by opa334** [comment]
Okay as it turns out only the
```xml
<key>com.apple.private.thread-set-state</key>
<true/>
```
entitlement is enough to make opainject work on iOS 16.4+

**Comment by iAroc** [comment]
Just tried it out, injection works fine on my 16.5 phone.

Thanks, didnt though it would be such a small thing
