### ISSUE TITLE
Code Signature Invalid Issue Encountered When Attempting Injection on iOS 16

### ISSUE THREAD

**Issue by qqwq122825** [opa334/opainject#7]

**Comment by qqwq122825** [comment]
I tried injecting dylib in a non-jailbroken environment and encountered 'Code Signature Invalid' error. In a jailbroken environment, the injection succeeds but the main program freezes.

**Comment by QuiYou** [comment]
I'm just like you

**Comment by QuiYou** [comment]
> 在非越狱环境下尝试注入dylib，出现Code Signature Invalid错误，在越狱环境下注入成功，但主程序卡死。

I'm just like you

**Comment by QuiYou** [comment]
> 在非越狱环境下尝试注入dylib，出现Code Signature Invalid错误，在越狱环境下注入成功，但主程序卡死。

If Code Signature Invalid appears, you can solve it by converting the dylib to rootless

**Comment by QuiYou** [comment]
> I tried injecting dylib in a non-jailbroken environment and encountered 'Code Signature Invalid' error. In a jailbroken environment, the injection succeeds but the main program freezes.

the dylib needs to have the same team id as the process it injects into

**Comment by opa334** [comment]
in a jb env, the dylib likely needs to be adhoc signed and added to trustcache already
in a non jb env, the dylib needs to be signed with the same team id as the process.
