### ISSUE TITLE
This is the problem I encountered in Troll

### ISSUE THREAD

**Issue by QuiYou** [opa334/opainject#8]
tetedeiPad# ./"command.sh"
 [spawnPacChild] Got task port 6403 for pid 4390
 OPAINJECT HERE WE ARE
 RUNNING AS 0
 Got task port 6403 for pid 4390!
 [prepareForMagic] done, ropLoop: 0x202DE30C8
 [createRemotePthread] Created bootstrap thread... now waiting on finish
 [createRemotePthread] Bootstrap done!
 [sandboxFixup] applying sandbox extension(s)! sandbox_extension_consume: 0x1EA7AEC64
 [arbCall] Set thread state for arbitary call
 [arbCall] Started thread, waiting for it to finish...
 [sandboxFixup] sandbox_extension_consume returned 6 for read extension
 [arbCall] Set thread state for arbitary call
 [arbCall] Started thread, waiting for it to finish...
 [sandboxFixup] sandbox_extension_consume returned 7 for executable extension
 [injectDylibViaRop] Preparation done, now injecting!
 [injectDylibViaRop] dlopen: 0x1AD5E6BE8, dlerror: 0x1AD5E8564
 [arbCall] Set thread state for arbitary call
 [arbCall] Started thread, waiting for it to finish...
 [arbCall] Set thread state for arbitary call
 [arbCall] Started thread, waiting for it to finish...
 [injectDylibViaRop] dlopen failed, error:
 dlopen(/var/mobile/Documents/libDylib.dylib, 0x0002): tried: '/var/mobile/Documents/libDylib.dylib' (code signature invalid in <A1DAF9F9-1C30-3D47-A560-FA6034885F76> '/private/var/mobile/Documents/libDylib.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0000CC00, codeBlobSize=0x00004980), '/private/preboot/Cryptexes/OS/var/mobile/Documents/libDylib.dylib' (no such file), '/var/mobile/Documents/libDylib.dylib' (code signature invalid in <A1DAF9F9-1C30-3D47-A560-FA6034885F76> '/private/var/mobile/Documents/libDylib.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0000CC00, codeBlobSize=0x00004980), '/private/var/mobile/Documents/libDylib.dylib' (code signature invalid in <A1DAF9F9-1C30-3D47-A560-FA6034885F76> '/private/var/mobile/Documents/libDylib.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0000CC00, codeBlobSize=0x00004980), '/private/preboot/Cryptexes/OS/private/var/mobile/Documents/libDylib.dylib' (no such file), '/private/var/mobile/Documents/libDylib.dylib' (code signature invalid in <A1DAF9F9-1C30-3D47-A560-FA6034885F76> '/private/var/mobile/Documents/libDylib.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0000CC00, codeBlobSize=0x00004980)
 [spawnPacChild] Child returned 0
 #
 tetedeiPad#

**Comment by opa334** [comment]
the dylib needs to have the same team id as the process it injects into

**Comment by QuiYou** [comment]
> dylib 需要与它注入的进程具有相同的团队 ID

code signature invalid in I have solved it but a new problem has arisen
![3061718443503_ pic](https://github.com/opa334/opainject/assets/75100822/295c88b1-67d6-4e28-8e81-c16921bdd2b9)

**Comment by BoringApp** [comment]
Put your dylib into target application's mainbundle to solve it
